export default {
    // API CONSTANTS
    API_CALL: 'API_CALL',
    API_TQ_RETURN: 'API_TQ_RETURN',
    API_TT_RETURN: 'API_TT_RETURN',
    API_SKU_RETURN: 'API_SKU_RETURN',
    API_HS_RETURN: 'API_HS_RETURN',
    // LISTENERS CONSTANTS
    TEQUILEROS_CHANGE: 'TEQUILEROS_CHANGE',
    TEQUILERA_CHANGE: 'TEQUILERA_CHANGE',
    BOTELLAS_CHANGE: 'BOTELLAS_CHANGE',
    // UTILS
    CHANGE_TEQUILERA: 'CHANGE_TEQUILERA',
}