export default {
    API_CALL: 'API_CALL',
    API_TQ_RETURN: 'API_TQ_RETURN',
    API_TT_RETURN: 'API_TT_RETURN',
    API_SKU_RETURN: 'API_SKU_RETURN',
    API_HS_RETURN: 'API_HS_RETURN',
    TEQUILEROS_CHANGE: 'TEQUILEROS_CHANGE',
}